spring.application.name=spring-feedback-app

# Server
server.port=8088

# H2 Database
spring.datasource.url=jdbc:h2:mem:feedback-app
#spring.datasource.url=jdbc:h2:file:~/doctor_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.settings.web-allow-others=true

# JPA
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

# H2 Console (very useful)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Reduce memory/log usage (good for low systems)
logging.level.root=INFO
spring.main.lazy-initialization=true


server.servlet.context-path=/spring-feedback-app
